version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hypeDatabase
    volumes:
      - './data:/data/db'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/hype
    ports:
      - "8000:8000"
    depends_on:
      - mongo
